insert into utilisateur values(id_utilisateur_sequence.nextval,'DA SILVA TEIXEIRA','David');
insert into utilisateur values(id_utilisateur_sequence.nextval,'RICHARD','Jeremy');
insert into utilisateur values(id_utilisateur_sequence.nextval,'Peyre','Leo');

commit;

insert into plante values(id_plante_sequence.nextval,'Butome en ombelle','Plante vivace de 50 cm à 1 mètre, glabre, à souchehorizontale charnue','Butomaceae');
insert into plante values(id_plante_sequence.nextval,'Muguet','Plante vivace de 30-60 cm, glabre, à souche horizontale épaisse très fibreuse','Asparagaceae');
insert into plante values(id_plante_sequence.nextval,'Digitale pourpre','Plante bisannuelle ou vivace de 50 cm à 1 m. 50, tomenteuse-blanchâtre, à tige robuste, creuse, lâchement feuillée','Plantaginaceae');
insert into plante values(id_plante_sequence.nextval,'Aspérule odorante','Plante vivace de 10-30 cm, glabre, noirâtre et odorante après la dessiccation, à souche grêle, longuement traçante','Rubiaceae');
insert into plante values(id_plante_sequence.nextval,'Lierre terrestre','Plante vivace, mollement poilue, couchée-radicante, à tiges florifères redressées, simples, longues de 5-25 cm','Lamiaceae');
insert into plante values(id_plante_sequence.nextval,'Cannabis','Plante annuelle de 1-2 mètres, pubescente-rude, à odeur forte','Cannabaceae');
insert into plante values(id_plante_sequence.nextval,'Houblon','Plante vivace de 2-5 mètres, rude, à tiges herbacées, sarmenteuses-volubiles, rameuses','Cannabaceae');
insert into plante values(id_plante_sequence.nextval,'Hysope','Plante vivace de 20-50 cm, glabre ou glabrescente, verte, aromatique','Lamiaceae');
insert into plante values(id_plante_sequence.nextval,'Iris fétide','Plante vivace de 30-80 cm, glabre, fétide par le froissement, à rhizome épais','Iridaceae');
insert into plante values(id_plante_sequence.nextval,'Iris faux acore','Plante vivace de 40 cm à 1 mètre, glabre, inodore, à rhizome épais','Iridaceae');
insert into plante values(id_plante_sequence.nextval,'Knautie des champs','Plante vivace de 20-80 cm, velue, à souche épaisse et oblique','Caprifoliaceae');
insert into plante values(id_plante_sequence.nextval,'Gesse des bois','Plante vivace de 1 à 2 mètres, glabre','Gesse des bois');
insert into plante values(id_plante_sequence.nextval,'Salicaire commune','Plante vivace de 50 cm, à 1 mètre, dressée, robuste, pubescente dans le haut, à souche épaisse','Lythraceae');
insert into plante values(id_plante_sequence.nextval,'Menthe pouliot','Plante vivace de 10-50 cm, velue-grisâtre ou glabrescente, à odeur très forte','Lamiaceae');
insert into plante values(id_plante_sequence.nextval,'Origan commun','Plante vivace de 30-80 cm, poilue, souvent rougeâtre, aromatique','Lamiaceae');
insert into plante values(id_plante_sequence.nextval,'Anémone pulsatille','Fleur médicinale vivace','Anémone pulsatille');
insert into plante values(id_plante_sequence.nextval,'Sauge des prés','Plante vivace de 35-80 cm, velue, simple ou peu rameuse, odorante','Lamiaceae');
insert into plante values(id_plante_sequence.nextval,'Scabieuse blanchâtre','Plante vivace de 20-40 cm, glabrescente, à tiges peu rameuses, feuillées','Caprifoliaceae');
insert into plante values(id_plante_sequence.nextval,'Silène penché','Plante vivace, velue, à souche presque ligneuse tiges de 20-50 cm, simples ou peu rameuses, visqueuses dans le haut, peu feuillées','Caryophyllaceae');
insert into plante values(id_plante_sequence.nextval,'Épiaire des bois','Ortie puante. Plante vivace de 30 cm à 1 mètre, très velue, verte, à souche rampante, à odeur fétide','Épiaire des bois');
insert into plante values(id_plante_sequence.nextval,'Petite pervenche','Plante vivace, glabre, couchée-diffuse, à tiges persistantes, radicantes, longues de 1-2 mètres','Apocynaceae');
insert into plante values(id_plante_sequence.nextval,'Violette des chiens','Tiges de 5-40 cm, herbacées, dressées ou ascendantes, naissant de la souche','Violaceae');
insert into plante values(id_plante_sequence.nextval,'Fusain d’Europe','Rameaux tétragones, verts feuilles moyennes, de 4-0 cm de long, elliptiques ou ovales-lancéolées','Celastraceae');
insert into plante values(id_plante_sequence.nextval,'Rosier des chiens','Arbrisseau de 1 à 3 mètres, généralement verdâtre et à rameaux robustes, dressés','Rosaceae');
insert into plante values(id_plante_sequence.nextval,'Rosier pimprenelle','Arbrisseau peu élevé, souvent nain, à souche traçante, aiguillons nombreux, droits, inégaux, entremêlés d acicules','Rosaceae');
insert into plante values(id_plante_sequence.nextval,'Viorne obier','Arbrisseau de 2-4 mètres, à rameaux fragiles, glabres, d un gris blanchâtre, Viorne obier','Viorne obier');
insert into plante values(id_plante_sequence.nextval,'Achillée millefeuille','Plante vivace à racine rampante tiges de 2-7 dm, dressées, pubescentes, parfois laineuses ainsi que les feuilles','Asteraceae');
insert into plante values(id_plante_sequence.nextval,'Bugle de Genève','Plante vivace de 10-40 cm, inodore, sans rejets rampants tiges dressées, simples, velues-laineuses tout autour, peu feuillées','Lamiaceae');
insert into plante values(id_plante_sequence.nextval,'Guimauve officinale','Plante vivace, toute veloutée-blanchâtre, à racine épaisse, blanche tiges d environ 1 mètre, dressées, robustes, Malvaceae','Malvaceae');
insert into plante values(id_plante_sequence.nextval,'Pâquerette','Plante à fibres, très grêles tiges, mesure 3-10 cm rarement plus, grêles','Asteraceae');

commit;

insert into caracteristique values(id_caracte_sequence.nextval,7,4,7,'Juin – Août');
insert into caracteristique values(id_caracte_sequence.nextval,2,2,6,'Mai -Juillet');
insert into caracteristique values(id_caracte_sequence.nextval,3,5,5,'Mai -Septembre');
insert into caracteristique values(id_caracte_sequence.nextval,3,4,2,'Mai – Juin');
insert into caracteristique values(id_caracte_sequence.nextval,4,4,4,'Mars – Mai');
insert into caracteristique values(id_caracte_sequence.nextval,3,5,7,'Juin-Septembre');
insert into caracteristique values(id_caracte_sequence.nextval,2,2,7,'Juin – Septembre');
insert into caracteristique values(id_caracte_sequence.nextval,2,6,4,'Juillet -Août');
insert into caracteristique values(id_caracte_sequence.nextval,6,4,6,'Mai – Juillet');
insert into caracteristique values(id_caracte_sequence.nextval,2,4,6,'Avril – Juillet');
insert into caracteristique values(id_caracte_sequence.nextval,3,5,5,'Juin – Août');
insert into caracteristique values(id_caracte_sequence.nextval,4,4,6,'Juin – Août');
insert into caracteristique values(id_caracte_sequence.nextval,5,6,7,'Juin – Septembre');
insert into caracteristique values(id_caracte_sequence.nextval,3,4,5,'Juillet – Octobre');
insert into caracteristique values(id_caracte_sequence.nextval,1,5,7,'Juillet – Septembre');
insert into caracteristique values(id_caracte_sequence.nextval,2,6,7,'Avril – Juin');
insert into caracteristique values(id_caracte_sequence.nextval,2,5,7,'Mai – Juillet');
insert into caracteristique values(id_caracte_sequence.nextval,3,5,5,'Juillet – Septembre');
insert into caracteristique values(id_caracte_sequence.nextval,4,4,3,'Mai – Juillet');
insert into caracteristique values(id_caracte_sequence.nextval,3,5,2,'Juin – Septembre');
insert into caracteristique values(id_caracte_sequence.nextval,3,5,2,'Février-Mai');
insert into caracteristique values(id_caracte_sequence.nextval,3,4,6,'Avril – Juin');
insert into caracteristique values(id_caracte_sequence.nextval,3,4,5,'Avril – Mai');
insert into caracteristique values(id_caracte_sequence.nextval,3,4,6,'Mai – Juin');
insert into caracteristique values(id_caracte_sequence.nextval,2,5,5,'Juin – Juillet');
insert into caracteristique values(id_caracte_sequence.nextval,4,4,5,'Mai – Juin');
insert into caracteristique values(id_caracte_sequence.nextval,3,4,7,'Juin – Septembre');
insert into caracteristique values(id_caracte_sequence.nextval,2,4,7,'Juin – Septembre');
insert into caracteristique values(id_caracte_sequence.nextval,4,5,6,'Juin – Août');
insert into caracteristique values(id_caracte_sequence.nextval,4,8,7,'Janvier – Décembre');

commit;

insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);
insert into posseder values(id_plante_posseder_sequence.nextval,id_caracte_posseder_sequence.nextval);

commit;

insert into choisir values(id_plante_choisir_sequence.nextval,1);
insert into choisir values(id_plante_choisir_sequence.nextval,1);
insert into choisir values(id_plante_choisir_sequence.nextval,1);
insert into choisir values(id_plante_choisir_sequence.nextval,1);
insert into choisir values(id_plante_choisir_sequence.nextval,1);
insert into choisir values(id_plante_choisir_sequence.nextval,1);
insert into choisir values(id_plante_choisir_sequence.nextval,1);
insert into choisir values(id_plante_choisir_sequence.nextval,1);
insert into choisir values(id_plante_choisir_sequence.nextval,1);
insert into choisir values(id_plante_choisir_sequence.nextval,1);
insert into choisir values(id_plante_choisir_sequence.nextval,2);
insert into choisir values(id_plante_choisir_sequence.nextval,2);
insert into choisir values(id_plante_choisir_sequence.nextval,2);
insert into choisir values(id_plante_choisir_sequence.nextval,2);
insert into choisir values(id_plante_choisir_sequence.nextval,2);
insert into choisir values(id_plante_choisir_sequence.nextval,2);
insert into choisir values(id_plante_choisir_sequence.nextval,2);
insert into choisir values(id_plante_choisir_sequence.nextval,2);
insert into choisir values(id_plante_choisir_sequence.nextval,2);
insert into choisir values(id_plante_choisir_sequence.nextval,2);
insert into choisir values(id_plante_choisir_sequence.nextval,3);
insert into choisir values(id_plante_choisir_sequence.nextval,3);
insert into choisir values(id_plante_choisir_sequence.nextval,3);
insert into choisir values(id_plante_choisir_sequence.nextval,3);
insert into choisir values(id_plante_choisir_sequence.nextval,3);
insert into choisir values(id_plante_choisir_sequence.nextval,3);
insert into choisir values(id_plante_choisir_sequence.nextval,3);
insert into choisir values(id_plante_choisir_sequence.nextval,3);
insert into choisir values(id_plante_choisir_sequence.nextval,3);
insert into choisir values(id_plante_choisir_sequence.nextval,3);

commit;